# Pull an official base image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Set the environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# RUN apt-get update && apt-get install -y \
#     pkg-config \
#     libmariadb-dev \
#     && ln -s /usr/bin/mariadb_config /usr/bin/mysql_config

# Install the dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy your application code to the container
COPY . .

# Run the web service on container startup. Here we use the gunicorn
# webserver, with one worker process and 8 threads.
# For environments with multiple CPU cores, increase the number of workers
# to be equal to the cores available.
# Timeout is set to 0 to disable the timeouts of the workers to allow Cloud Run to handle instance scaling.
CMD exec gunicorn --bind :8080 --workers 1 --threads 8 --timeout 0 eai.wsgi:application